services:
  - type: web
    name: ezyago-trading
    env: python
    region: frankfurt
    plan: starter
    pythonVersion: 3.11.9
    buildCommand: |
      python3.11 -m venv .venv
      . .venv/bin/activate
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app.main:app --bind 0.0.0.0:$PORT --workers 1 --worker-class uvicorn.workers.UvicornWorker --timeout 120 --access-logfile -
    envVars:
      - key: ENVIRONMENT
        value: PRODUCTION
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONPATH
        value: /opt/render/project/src
    healthCheckPath: /health
    autoDeploy: true
