services:
  - type: web
    name: ezyago-trading
    env: python
    region: frankfurt
    plan: starter
    buildCommand: |
      pip install --upgrade pip==24.0
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app.main:app --bind 0.0.0.0:$PORT --workers 1 --worker-class uvicorn.workers.UvicornWorker --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ENVIRONMENT
        value: PRODUCTION
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONPATH
        value: /opt/render/project/src
    healthCheckPath: /health
    autoDeploy: true
